/*
 * This source file was generated by the Gradle 'init' task
 */
package func;

public class SimpleFunc {
    public static String getGreeting() {
        return "Hello World from module!";
    }
}
